double *grad_0_E0      = deriv_base +  0 * BLK_SZ;
double *grad_1_E0      = deriv_base +  1 * BLK_SZ;
double *grad_2_E0      = deriv_base +  2 * BLK_SZ;

double *grad_0_E1      = deriv_base +  3 * BLK_SZ;
double *grad_1_E1      = deriv_base +  4 * BLK_SZ;
double *grad_2_E1      = deriv_base +  5 * BLK_SZ;

double *grad_0_E2      = deriv_base +  6 * BLK_SZ;
double *grad_1_E2      = deriv_base +  7 * BLK_SZ;
double *grad_2_E2      = deriv_base +  8 * BLK_SZ;

double *grad_0_A0      = deriv_base +  9 * BLK_SZ;
double *grad_1_A0      = deriv_base + 10 * BLK_SZ;
double *grad_2_A0      = deriv_base + 11 * BLK_SZ;

double *grad_0_A1      = deriv_base + 12 * BLK_SZ;
double *grad_1_A1      = deriv_base + 13 * BLK_SZ;
double *grad_2_A1      = deriv_base + 14 * BLK_SZ;

double *grad_0_A2      = deriv_base + 15 * BLK_SZ;
double *grad_1_A2      = deriv_base + 16 * BLK_SZ;
double *grad_2_A2      = deriv_base + 17 * BLK_SZ;

double *grad_0_psi     = deriv_base + 18 * BLK_SZ;
double *grad_1_psi     = deriv_base + 19 * BLK_SZ;
double *grad_2_psi     = deriv_base + 20 * BLK_SZ;

double *grad2_0_0_psi  = deriv_base + 21 * BLK_SZ;
double *grad2_1_1_psi  = deriv_base + 22 * BLK_SZ;
double *grad2_2_2_psi  = deriv_base + 23 * BLK_SZ;

double *grad_0_Gamma   = deriv_base + 24 * BLK_SZ;
double *grad_1_Gamma   = deriv_base + 25 * BLK_SZ;
double *grad_2_Gamma   = deriv_base + 26 * BLK_SZ;

double *grad2_0_0_A0   = deriv_base + 27 * BLK_SZ;
double *grad2_1_1_A0   = deriv_base + 28 * BLK_SZ;
double *grad2_2_2_A0   = deriv_base + 29 * BLK_SZ;

double *grad2_0_0_A1   = deriv_base + 30 * BLK_SZ;
double *grad2_1_1_A1   = deriv_base + 31 * BLK_SZ;
double *grad2_2_2_A1   = deriv_base + 32 * BLK_SZ;

double *grad2_0_0_A2   = deriv_base + 33 * BLK_SZ;
double *grad2_1_1_A2   = deriv_base + 34 * BLK_SZ;
double *grad2_2_2_A2   = deriv_base + 35 * BLK_SZ;

// === First derivatives of phi (Ψ) ===
double *grad_0_phi     = deriv_base + 36 * BLK_SZ;
double *grad_1_phi     = deriv_base + 37 * BLK_SZ;
double *grad_2_phi     = deriv_base + 38 * BLK_SZ;